[package]
name = "ruxel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.12.1"
bevy_ecs = { version = "0.12.1", features = ["multi-threaded"] }
env_logger = "0.10.1"
log = "0.4.20"
wgpu = "0.19.1"
winit = "0.29.10"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[lints.clippy]
type_complexity = "allow"
