[package]
name = "ruxel"
authors = ["ItsSunnyMonster"]
description = "A voxel engine written in Rust."
readme = "README.md"
repository = "https://github.com/ItsSunnyMonster/ruxel"
keywords = ["voxel", "engine", "rust", "game", "open-source"]
categories = ["game-development", "graphics", "game-engines"]
version = "0.1.0-indev"
edition = "2021"
license = "MIT and Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.13.2"
bevy_ecs = { version = "0.13.2", features = ["multi-threaded"] }
env_logger = "0.11.3"
log = "0.4.21"
pollster = "0.3.0"
wgpu = "0.19.3"
winit = "0.29.15"
raw-window-handle = "0.6.0"
log-panics = { version = "2", features = ["with-backtrace"]}
cfg-if = "1.0.0"
humantime = { version = "2.1.0"}
macros = { path = "crates/macros" }

# Dependencies for file logging
fern = { version = "0.6.2", features = ["colored"], optional = true }
chrono = { version = "0.4.37", optional = true }
flate2 = { version = "1.0.28", optional = true }

[features]
log-to-file = ["dep:fern", "dep:flate2", "dep:chrono"]
windowed = []
dist = ["log-to-file", "windowed"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[lints.clippy]
type_complexity = "allow"

[build-dependencies]
winres = "0.1.12"

[profile.dist]
inherits = "release"
strip = true
lto = true
