[package]
name = "ruxel"
authors = ["ItsSunnyMonster"]
description = "A voxel engine written in Rust."
readme = "README.md"
repository = "https://github.com/ItsSunnyMonster/ruxel"
keywords = ["voxel", "engine", "rust", "game", "open-source"]
categories = ["game-development", "graphics", "game-engines"]
version = "0.1.0-indev"
edition = "2021"
license = "MIT and Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.13.2"
bevy_ecs = { version = "0.13.2", features = ["multi-threaded"] }
log = "0.4.21"
fern = { version = "0.6.2", features = ["colored"] }
pollster = "0.3.0"
wgpu = "0.20.0"
winit = "0.30.0"
raw-window-handle = "0.6.1"
log-panics = { version = "2", features = ["with-backtrace"]}
cfg-if = "1.0.0"
humantime = { version = "2.1.0"}
owo-colors = "4.0.0"
ruxel_macros = { path = "crates/ruxel_macros" }

# Dependencies for file logging
chrono = { version = "0.4.38", optional = true }
flate2 = { version = "1.0.30", optional = true }

[features]
default = ["log-to-console"]
log-to-file = ["dep:flate2", "dep:chrono"]
log-to-console = []
windowed = []
dist = ["log-to-file", "windowed"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[lints.clippy]
type_complexity = "allow"
missing_docs_in_private_items = "deny"

[build-dependencies]
winres = "0.1.12"

[profile.dist]
inherits = "release"
strip = true
lto = true
