[package]
name = "smve_macros"
version = "0.1.1"
edition = "2021"
description = "Macro implementations for smve"
license = "MIT OR Apache-2.0"
repository = "https://github.com/smve-rs/smve"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.61"
quote = "1.0.36"
