name: Report CI Status

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - master

jobs:
  report:
    name: Report CI Status
    runs-on: ubuntu-latest
    steps:
      - name: On Failed
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.CI_GIST_TOKEN }}
          gistID: a488eb0391a5fc6a2918d13184cd0a26
          filename: vuxt_ci.svg
          label: CI
          message: Failing
          logoColor: cdd6f4
          labelColor: 313244
          color: f38ba8
          namedLogo: github
          style: for-the-badge

      - name: On Success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.CI_GIST_TOKEN }}
          gistID: a488eb0391a5fc6a2918d13184cd0a26
          filename: vuxt_ci.json
          label: CI
          message: Passing
          logoColor: cdd6f4
          labelColor: 313244
          color: a6e3a1
          namedLogo: github
          style: for-the-badge